/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        int table[26]={0};
        int s_length = s.length();
        int t_length = t.length();
        //find char in s
        for(int i = 0; i < s_length; ++i)
        {
            table[s[i] - 'a']++;
        }
      //remove common char between s and t and adding uncommon char
        for(int i = 0; i < t_length; ++i)
        {
            if(table[t[i] - 'a'])
                table[t[i] - 'a']--;
            else
                table[t[i] - 'a']++;
        }
      //finding uncommon char
        int i = 0;
        for(i = 0; i < 26; ++i)
            if(table[i])
                break;
        
        return ('a'+i);
         
    }
};
